-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 09:49:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema dbquedan3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbquedan3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbquedan3` DEFAULT CHARACTER SET utf8 ;
USE `dbquedan3` ;

-- -----------------------------------------------------
-- Table `dbquedan3`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`proveedores` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(255) NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`facturas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_fac` DATE NOT NULL,
  `num_fac` BIGINT(20) NOT NULL,
  `monto` DECIMAL(17,2) NOT NULL,
  `proveedor_id` BIGINT(20) UNSIGNED NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `added` INT(11) NOT NULL COMMENT 'Su propósito es controlar si la factura ha sido o no asociada con un quedan. Cero indica que aun no lo ha sido; un número distinto de cero quiere decir que fue asociada y ese número será el mismo id de quedan al que  se asoció. Por default se insertará 0 cuando se cree la factura.',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `facturas_proveedor_id_foreign`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dbquedan3`.`proveedores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`fuentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`fuentes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_fuente` VARCHAR(255) NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`proyectos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(255) NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`quedans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`quedans` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `num_quedan` BIGINT(20) NOT NULL,
  `fecha_emi` DATE NOT NULL,
  `cant_num` DECIMAL(17,2) NOT NULL,
  `fuente_id` BIGINT(20) UNSIGNED NOT NULL,
  `proyecto_id` BIGINT(20) UNSIGNED NOT NULL,
  `proveedor_id` BIGINT(20) UNSIGNED NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_quedans_proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `dbquedan3`.`proveedores` (`id`),
  CONSTRAINT `quedans_fuente_id_foreign`
    FOREIGN KEY (`fuente_id`)
    REFERENCES `dbquedan3`.`fuentes` (`id`),
  CONSTRAINT `quedans_proyecto_id_foreign`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `dbquedan3`.`proyectos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`quedanfacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`quedanfacturas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `factura_id` BIGINT(20) UNSIGNED NOT NULL,
  `quedan_id` BIGINT(20) UNSIGNED NOT NULL,
  `hiden` INT(11) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_quedanfacturas_facturas1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `dbquedan3`.`facturas` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `quedanfacturas_quedan_id_foreign`
    FOREIGN KEY (`quedan_id`)
    REFERENCES `dbquedan3`.`quedans` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `dbquedan3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbquedan3`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
